# Generated by Django 4.0.3 on 2023-04-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
